import type { Env } from "@/env";

type JsonObject = Record<string, unknown>;

export type UsableFragment = {
  id: string;
  workspaceId?: string;
  fragmentTypeId?: string;
  key?: string;
  title?: string;
  content?: string;
  tags?: string[];
  frontmatter?: JsonObject;
};

type CreateFragmentInput = {
  workspaceId: string;
  fragmentTypeId: string;
  key: string;
  title: string;
  summary: string;
  content: string;
  tags: string[];
  createdAt?: string;
};

type UpdateFragmentInput = {
  fragmentTypeId: string;
  title: string;
  summary: string;
  content: string;
  tags: string[];
};

function asRecord(value: unknown): JsonObject | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  return value as JsonObject;
}

/**
 * Usable's REST responses do NOT include the parsed `frontmatter` JSONB
 * column (it's an internal search projection; verified against usable's
 * `getMemoryFragmentById` select) — but stored `content` retains the YAML
 * block verbatim, so parse it out here. Mirrors usable's own
 * `parseFrontmatter` (packages/core/src/utils/frontmatter.ts): first line
 * exactly `---`, closed by a `---` (or `...`) line, YAML between.
 */
export function frontmatterFromContent(
  content: string | undefined,
): JsonObject | null {
  if (!content) return null;
  const lines = content.trim().split("\n");
  if (lines[0]?.trim() !== "---") return null;
  const end = lines.findIndex(
    (line, i) => i > 0 && (line.trim() === "---" || line.trim() === "..."),
  );
  if (end === -1) return null;
  try {
    return asRecord(Bun.YAML.parse(lines.slice(1, end).join("\n")));
  } catch {
    return null;
  }
}

function normalizeFragment(value: unknown): UsableFragment | null {
  const obj = asRecord(value);
  if (!obj) return null;
  const id = typeof obj?.id === "string" ? obj.id : undefined;
  if (!id) return null;
  const content = typeof obj.content === "string" ? obj.content : undefined;
  return {
    id,
    workspaceId:
      typeof obj.workspaceId === "string" ? obj.workspaceId : undefined,
    fragmentTypeId:
      typeof obj.fragmentTypeId === "string" ? obj.fragmentTypeId : undefined,
    key: typeof obj.key === "string" ? obj.key : undefined,
    title: typeof obj.title === "string" ? obj.title : undefined,
    content,
    tags: Array.isArray(obj.tags)
      ? obj.tags.filter((tag): tag is string => typeof tag === "string")
      : undefined,
    frontmatter:
      asRecord(obj.frontmatter) ?? frontmatterFromContent(content) ?? undefined,
  };
}

function hasTaggedKey(fragment: UsableFragment, key: string) {
  return (
    fragment.tags?.includes(`fragment-key:${key}`) ||
    fragment.tags?.includes(`state-key:${key}`)
  );
}

function keysFromFragment(fragment: UsableFragment) {
  const keys = new Set<string>();
  if (fragment.key) keys.add(fragment.key);
  for (const tag of fragment.tags ?? []) {
    const match = tag.match(/^fragment-key:(.+)$/);
    if (match?.[1]) keys.add(match[1]);
  }
  if (fragment.content) {
    const match =
      fragment.content.match(/\nkey:\s*"([^"]+)"/) ??
      fragment.content.match(/\nkey:\s*([^\n]+)/);
    if (match?.[1]) keys.add(match[1].trim().replace(/^"|"$/g, ""));
  }
  return keys;
}

function contentHasKey(fragment: UsableFragment, key: string) {
  if (!fragment.content) return false;
  if (fragment.content.includes(`key: "${key}"`)) return true;
  try {
    const parsed = JSON.parse(fragment.content) as Record<string, unknown>;
    return parsed.key === key;
  } catch {
    return false;
  }
}

async function readJson(response: Response) {
  const text = await response.text();
  if (!response.ok) {
    throw new Error(`Usable API HTTP ${response.status}: ${text}`);
  }
  return text.trim() ? (JSON.parse(text) as unknown) : {};
}

function parseFragmentEnvelope(json: unknown) {
  const root = asRecord(json);
  const fragment = normalizeFragment(root?.fragment ?? root?.data ?? json);
  if (fragment) return fragment;
  const fragmentId =
    typeof root?.fragmentId === "string" ? root.fragmentId : undefined;
  if (!fragmentId) return null;
  return {
    id: fragmentId,
    key: typeof root?.key === "string" ? root.key : undefined,
  };
}

export class UsableApiClient {
  constructor(private readonly env: Env) {}

  private request(path: string, init: RequestInit = {}) {
    const headers = new Headers(init.headers);
    headers.set("accept", "application/json");
    headers.set("authorization", `Bearer ${this.env.USABLE_API_TOKEN}`);
    // FormData must set its own content-type: the multipart boundary is
    // generated by fetch, and naming the type here would strip it.
    if (
      init.body != null &&
      !(init.body instanceof FormData) &&
      !headers.has("content-type")
    ) {
      headers.set("content-type", "application/json");
    }
    return fetch(`${this.env.USABLE_API_BASE_URL}${path}`, {
      ...init,
      headers,
    });
  }

  async getFragmentByKey(workspaceId: string, key: string) {
    const directParams = new URLSearchParams({ workspaceId });
    const direct = await this.request(
      `/memory-fragments/${encodeURIComponent(key)}?${directParams.toString()}`,
    );
    if (direct.ok) {
      return parseFragmentEnvelope(await readJson(direct));
    }

    const params = new URLSearchParams({
      workspaceId,
      limit: "100",
      offset: "0",
    });
    const json = await readJson(
      await this.request(`/memory-fragments?${params.toString()}`),
    );
    const root = asRecord(json);
    const rows = Array.isArray(root?.fragments) ? root.fragments : [];
    const fragments = rows
      .map((row) => normalizeFragment(row))
      .filter((fragment): fragment is UsableFragment => fragment != null);
    return (
      fragments.find((fragment) => fragment.key === key) ??
      fragments.find((fragment) => hasTaggedKey(fragment, key)) ??
      fragments.find((fragment) => contentHasKey(fragment, key)) ??
      null
    );
  }

  async listFragments(input: {
    workspaceId: string;
    fragmentTypeId: string;
    status?: string;
  }) {
    const fragments: UsableFragment[] = [];
    const limit = 500;
    let offset = 0;
    let totalCount = Number.POSITIVE_INFINITY;
    while (offset < totalCount) {
      const params = new URLSearchParams({
        workspaceId: input.workspaceId,
        fragmentTypeId: input.fragmentTypeId,
        limit: String(limit),
        offset: String(offset),
      });
      if (input.status) params.set("status", input.status);
      const json = await readJson(
        await this.request(`/memory-fragments?${params.toString()}`),
      );
      const root = asRecord(json);
      const rows = Array.isArray(root?.fragments) ? root.fragments : [];
      const page = rows
        .map((row) => normalizeFragment(row))
        .filter((fragment): fragment is UsableFragment => fragment != null);
      fragments.push(...page);
      const count = typeof root?.count === "number" ? root.count : page.length;
      totalCount =
        typeof root?.totalCount === "number" ? root.totalCount : offset + count;
      if (count === 0) break;
      offset += count;
    }
    return fragments;
  }

  async listFragmentKeys(input: {
    workspaceId: string;
    fragmentTypeId: string;
    status?: string;
  }) {
    const keys = new Set<string>();
    for (const fragment of await this.listFragments(input)) {
      for (const key of keysFromFragment(fragment)) keys.add(key);
    }
    return keys;
  }

  /**
   * Fetch one fragment by id. List rows usually already carry frontmatter
   * (parsed out of `content` by `normalizeFragment`), so this detail fetch is
   * the fallback for rows whose content lacked the YAML block. Returns null
   * ONLY on 404 (fragment gone — callers may safely skip it); any other
   * failure throws so a transient Usable 5xx is distinguishable from a
   * deletion.
   */
  async getFragmentById(fragmentId: string, workspaceId: string) {
    const params = new URLSearchParams({ workspaceId });
    const resp = await this.request(
      `/memory-fragments/${encodeURIComponent(fragmentId)}?${params.toString()}`,
    );
    if (resp.status === 404) return null;
    const json = await readJson(resp);
    const root = asRecord(json);
    return normalizeFragment(root?.fragment ?? root?.data ?? json);
  }

  async createFragment(input: CreateFragmentInput) {
    const json = await readJson(
      await this.request("/memory-fragments", {
        method: "POST",
        body: JSON.stringify(input),
      }),
    );
    return parseFragmentEnvelope(json);
  }

  async updateFragment(fragmentId: string, input: UpdateFragmentInput) {
    const json = await readJson(
      await this.request(`/memory-fragments/${fragmentId}`, {
        method: "PATCH",
        body: JSON.stringify(input),
      }),
    );
    return parseFragmentEnvelope(json);
  }

  /**
   * Upload a file and (optionally) attach it to a fragment in the same call.
   *
   * One multipart POST does both — `fragmentId` in the form body is Usable's
   * documented upload-and-attach path, so there is no separate attach step to
   * fail halfway. There is also no "request an upload URL" step: that exists
   * only as an MCP tool, which mints a token for this very endpoint. A Bearer
   * token posts here directly.
   *
   * The upload is asynchronous on Usable's side — a 200 means "accepted",
   * with `status: "uploading"`, and the bytes land shortly after. Callers must
   * not read a 200 as "the file is servable": the attachment row carries its
   * own status (see `listFragmentAttachments`), and that is what knows.
   * (`GET /files/:id/status` also exists upstream if a caller ever needs to
   * block on completion — deliberately not wrapped until something does.)
   */
  async uploadFile(input: {
    workspaceId: string;
    fileName: string;
    mimeType: string;
    bytes: Uint8Array;
    /** Attach to this fragment as part of the upload. */
    fragmentId?: string;
    tags?: string[];
  }) {
    const form = new FormData();
    // Copied into a plain ArrayBuffer: a `Buffer` is a view into Node's
    // shared allocation pool, which is neither what `Blob` accepts nor
    // something to hand to an async upload.
    const bytes = new Uint8Array(input.bytes);
    form.set(
      "file",
      new Blob([bytes], { type: input.mimeType }),
      input.fileName,
    );
    form.set("workspaceId", input.workspaceId);
    if (input.fragmentId) form.set("fragmentId", input.fragmentId);
    if (input.tags?.length) form.set("tags", JSON.stringify(input.tags));
    const json = await readJson(
      await this.request("/files/upload", { method: "POST", body: form }),
    );
    const root = asRecord(json);
    const fileId = typeof root?.fileId === "string" ? root.fileId : undefined;
    if (!fileId) throw new Error("Usable file upload returned no fileId");
    return {
      fileId,
      status: typeof root?.status === "string" ? root.status : "uploading",
    };
  }

  /**
   * Files attached to a fragment. Note the path: attachments hang off
   * `/fragments/:id/files`, NOT `/memory-fragments/:id` — reading the
   * fragment itself returns no attachment list at all.
   */
  async listFragmentAttachments(fragmentId: string) {
    const json = await readJson(
      await this.request(`/fragments/${encodeURIComponent(fragmentId)}/files`),
    );
    const rows = asRecord(json)?.attachments;
    if (!Array.isArray(rows)) return [];
    return rows
      .map((row) => {
        const attachment = asRecord(row);
        const fileId =
          typeof attachment?.fileId === "string"
            ? attachment.fileId
            : undefined;
        if (!attachment || !fileId) return null;
        // `file` is absent while an upload is still in flight, and its name
        // field is `name`, not `fileName`.
        const file = asRecord(attachment.file);
        return {
          fileId,
          fileName: typeof file?.name === "string" ? file.name : undefined,
          mimeType:
            typeof file?.mimeType === "string" ? file.mimeType : undefined,
          sizeBytes:
            typeof file?.sizeBytes === "number" ? file.sizeBytes : undefined,
          description:
            typeof attachment.description === "string"
              ? attachment.description
              : undefined,
          status:
            typeof attachment.status === "string"
              ? attachment.status
              : undefined,
        };
      })
      .filter((row): row is NonNullable<typeof row> => row != null);
  }

  /**
   * Raw bytes of a file. Returns the upstream Response so callers can stream
   * it straight through instead of buffering an image in memory.
   */
  downloadFile(fileId: string) {
    return this.request(`/files/${encodeURIComponent(fileId)}/download`);
  }
}
